polls/polls/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include("pollsapp.urls"))
]

polls/pollsapp/urls.py
from django.urls import path
from . import views

app_name = "pollsapp"

urlpatterns = [
    path('', views.index, name="index"),
    path('<int:question_id>', views.detail, name="detail"),
    path('<int:question_id>/result/', views.result, name="result"),
    path('<int:question_id>/vote/', views.vote, name="vote")
]

polls/pollsapp/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
    question = models.CharField(max_length=200)
    date = models.DateTimeField('date published')

    def __str__(self):
        return f"{self.question}"


class Choice(models.Model):
    question_id = models.ForeignKey(Question, on_delete=models.CASCADE, related_name="choices")
    choice = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    class Meta:
        ordering = ['id']

    def __str__(self):
        return f"{self.choice}. Votes: {self.votes}"

polls/pollsapp/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.db.models import Sum, Q
from .models import Question, Choice

# Create your views here.

def index(request):
    search_query = request.GET.get("search")
    
    if search_query:
        latest_question_list = Question.objects.filter(Q(question__icontains=search_query) | Q(date__icontains=search_query))
        header = f"Search results for: '{search_query}'"
    else:
        latest_question_list = Question.objects.order_by('-date')[:5]
        header = "Recent questions"

    votes_num = [num.choices.aggregate(Sum('votes'))['votes__sum'] for num in latest_question_list]

    questions_votes = zip(latest_question_list, votes_num)
    return render(request, "pollsapp/index.html", {
        "questions_votes": questions_votes,
        "header": header
    })


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    return render(request, "pollsapp/detail.html", {
        "question": question
    })


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choices.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        return render(request, "pollsapp/detail.html", {
            "question": question,
            "error_message": "You didn't select a choice."
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()

        return HttpResponseRedirect(reverse('pollsapp:result', args=(question.id,)))


def result(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    data = {
        "labels": [choice.choice for choice in question.choices.all()],
        "values": [vote.votes for vote in question.choices.all()]
    }

    return render(request, "pollsapp/result.html", {
        "question": question,
        "data": data
    })

polls/pollsapp/templates/pollsapp/detail.html
{% extends 'pollsapp/layout.html' %}
{% load static %}


{% block head %}
    <link rel="stylesheet" href="{% static 'pollsapp/css/detail.css' %}">
    <title>Question #{{ question.id }}</title>
{% endblock %}


{% block body %}
    <div class="container">
        <h1 id="question-header">{{ question.question }}</h1>
        <form action="{% url 'pollsapp:vote' question.id %}" method="post">
            {% csrf_token %}
            {% if error_message %}
                <p id="error-message">{{ error_message }}</p>
            {% endif %}

            {% for choice in question.choices.all %}
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                    <label class="form-check-label" for="choice{{ forloop.counter }}">{{ choice.choice }}</label>
                </div>
            {% endfor %}
            <button class="btn btn-primary" type="submit">Vote</button>
        </form>
    </div>
{% endblock %}

polls/pollsapp/templates/pollsapp/index.html
{% extends 'pollsapp/layout.html' %}
{% load static %}


{% block head %}
    <link rel="stylesheet" href="{% static 'pollsapp/css/index.css' %}">
    <title>Main page</title>
{% endblock %}


{% block body %}
    <h2 id="index-header">{{ header }}</h2>

    <ol class="list-group list-group-numbered">
    {% for question, votes in questions_votes %}
        <li class="list-group-item d-flex justify-content-between align-items-start">
            <div class="ms-2 me-auto">
                <div class="fw-bold"><a href="{% url 'pollsapp:detail' question.id %}" class="list-link">{{ question.question }}</a></div>
                {{ question.date }}
            </div>
            <span class="badge bg-primary rounded-pill">
                votes: {{ votes }}
            </span>
        </li>
    {% empty %}
        <p>No polls are available.</p>
    {% endfor %}
    </ol>
{% endblock %}

polls/pollsapp/templates/pollsapp/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'pollsapp/css/layout.css' %}">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    {% block head %}
    {% endblock %}
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'pollsapp:index' %}">POLLSAPP</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'pollsapp:index' %}">Home</a></li>
                        <!-- <li class="nav-item"><a class="nav-link active" href="#">Link</a></li> -->
                        <!-- <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Dropdown</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="#">Action</a></li>
                                <li><a class="dropdown-item" href="#">Another action</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="#">Something else here</a></li>
                            </ul>
                        </li> -->
                    </ul>
                    <form class="d-flex" action="{% url 'pollsapp:index' %}">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <main>
        <div class="wrapper">
            <div class="content">
                {% block body %}
                {% endblock %}
            </div>
        </div>
    </main>
    <!-- Charts.js -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
</body>
</html>

polls/pollsapp/templates/pollsapp/result.html
{% extends 'pollsapp/layout.html' %}
{% load static %}


{% block head %}
    <link rel="stylesheet" href="{% static 'pollsapp/css/result.css' %}">
    <title>Result #{{ question.id }}</title>
{% endblock %}


{% block body %}
    <h1 id="result-headline">Results for question "{{ question.question }}"</h1>
    <div class="votes-box">
        <div class="votes-list">
            <ul class="list-group">
            {% for choice in question.choices.all %}
                <li class="list-group-item">{{ choice.choice }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
            {% endfor %}
            </ul>
        </div>

        <div class="votes-chart">
            <canvas id="result-chart"></canvas>
        </div>
    </div>

    <nav aria-label="Page navigation example">
        <ul class="pagination">
            <li class="page-item"><a class="page-link" href="{% url 'pollsapp:detail' question.id %}">Vote again?</a></li>
        </ul>
    </nav>

    {{ data|json_script:"data" }}
    <script type="text/javascript" src="{% static 'pollsapp/js/chart.js' %}"></script>
{% endblock %}